/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED
#define CONFIG_SDIO 1
#undef  CONFIG_USB
#undef  USE_GENL_BT_STACK
#define USE_BLUEZ_BT_STACK 1
#define BYPASS_TX_DATA_PATH 1
#define BYPASS_RX_DATA_PATH 1
#define AMPDU_AGGR_SUPPORT 1
#define ONEBOX_DEBUG_ENABLE 1
#define CHIP_ENABLED 1
#define AUTO_RATE_SUPPORT 1
#undef  EEPROM_READ_EN
#define RSI_SDIO_MULTI_BLOCK_SUPPORT 1
#define SECURITY_SUPPORT 1
#define ENABLE_P2P_SUPPORT 1
#define IEEE80211_AMPDU_AGE 1
